sudo: required
services:
  - docker

before_install:
  - docker build -t matheus06/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matheus06/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  name : "docker-react"
  env : "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-069525858191"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
